blank_issues_enabled: true
contact_links:
  - name: ğŸ“„ ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆå‚ç…§
    url: https://qiita.com/konatsu_p/items/dfe199ebe3a7d2010b3e
    about: è³ªå•ã™ã‚‹å‰ã«ã€ã¾ãšã“ã¡ã‚‰ã®ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã‚’ç¢ºèªã—ã¦ãã ã•ã„ã€‚
